export const KTV_SONG_LIST = [
  // 1-11
  { title: "第一次爱的人", artist: "王心凌" },
  { title: "突然的自我", artist: "伍佰 & China Blue" },
  { title: "猜不透", artist: "丁当" },
  { title: "孤勇者（《英雄联盟：双城之战》动画剧集中文主题曲）", artist: "陈奕迅" },
  { title: "带我去找夜生活", artist: "告五人" },
  { title: "就让这大雨全都落下", artist: "容祖儿" },
  { title: "雨爱（电视剧《海派甜心》片尾曲）", artist: "杨丞琳" },
  { title: "11", artist: "队长 / 黄礼格" },
  { title: "雅俗共赏", artist: "许嵩" },
  { title: "你不是真正的快乐", artist: "五月天" },
  { title: "可能", artist: "程响" },
  // 12-22
  { title: "撕夜", artist: "阿杜" },
  { title: "笼（电影《消失的她》片尾主题曲）", artist: "张碧晨" },
  { title: "时光洪流", artist: "程响" },
  { title: "大鱼（动画《大鱼海棠》印象曲）", artist: "周深" },
  { title: "红色高跟鞋（电影《爱呼2：爱情左右》主题曲）", artist: "蔡健雅" },
  { title: "当你孤单你会想起谁", artist: "张栋梁" },
  { title: "童话", artist: "光良" },
  { title: "Dear John(Album Version)", artist: "王雪娥" },
  { title: "窗", artist: "虎二" },
  { title: "目及皆是你", artist: "小蓝背心" },
  { title: "盛夏的果实", artist: "莫文蔚" },
  // 23-33
  { title: "单身情歌", artist: "林志炫" },
  { title: "知足", artist: "五月天" },
  { title: "如果这就是爱情", artist: "张靓颖" },
  { title: "左边(电视剧《奋斗》插曲)", artist: "杨丞琳" },
  { title: "天若有情 (电视剧《锦绣未央》主题曲)", artist: "A-Lin" },
  { title: "想见你想见你想见你 (电视剧《想见你》片尾曲)", artist: "八三夭" },
  { title: "最熟悉的陌生人", artist: "萧亚轩" },
  { title: "如果你也听说", artist: "张惠妹" },
  { title: "天黑黑", artist: "孙燕姿" },
  { title: "倔强", artist: "五月天" },
  { title: "一千年以后", artist: "林俊杰" },
  // 34-44
  { title: "当爱在靠近 (电视剧《向左走向右走》片尾曲)", artist: "刘若英" },
  { title: "泡沫", artist: "G.E.M.邓紫棋" },
  { title: "情歌", artist: "梁静茹" },
  { title: "唯一(电影《恋爱通告》插曲)", artist: "王力宏" },
  { title: "爱人错过", artist: "告五人" },
  { title: "别怕我伤心", artist: "张信哲" },
  { title: "有多少爱可以重来", artist: "迪克牛仔" },
  { title: "告白气球", artist: "周杰伦" },
  { title: "修炼爱情", artist: "林俊杰" },
  { title: "开始懂了", artist: "孙燕姿" },
  { title: "忘记时间 (电视剧《仙剑奇侠传3》片尾曲)", artist: "胡歌" },
  // 45-55
  { title: "怎样", artist: "戴佩妮" },
  { title: "说爱你(电影《我要飞上天》主题曲)", artist: "蔡依林" },
  { title: "情非得已(电视剧《流星花园》主题曲)", artist: "庾澄庆" },
  { title: "蓝莲花 (电影《从你的全世界路过》插曲)", artist: "许巍" },
  { title: "爱你", artist: "王心凌" },
  { title: "给你一瓶魔法药水", artist: "告五人" },
  { title: "遇见 (电影《向左走向右走》主题曲)", artist: "孙燕姿" },
  { title: "夜的第七章", artist: "周杰伦" },
  { title: "晴天", artist: "周杰伦" },
  { title: "手放开", artist: "李圣杰" },
  { title: "就是爱你", artist: "陶喆" },
  // 56-63 (Previous additions)
  { title: "不得不爱", artist: "弦子 / 潘玮柏" },
  { title: "黄昏", artist: "周传雄" },
  { title: "半岛铁盒", artist: "周杰伦" },
  { title: "四季予你", artist: "程响" },
  { title: "Letting Go", artist: "蔡健雅" },
  { title: "你要的全拿走", artist: "胡彦斌" },
  { title: "你的背包", artist: "陈奕迅" },
  { title: "老人与海", artist: "海鸣威 / 吴琼" },
  // Set 2 (Previous additions)
  { title: "你的微笑(电视剧《一又二分之一的夏天》插曲)", artist: "F.I.R.飞儿乐团" },
  { title: "阴天", artist: "莫文蔚" },
  { title: "太美丽", artist: "陶喆" },
  { title: "我(国语)", artist: "张国荣" },
  { title: "爱", artist: "莫文蔚" },
  { title: "继续给十五岁的自己", artist: "刘若英" },
  { title: "会呼吸的痛", artist: "梁静茹" },
  { title: "Lydia(电视剧《斗鱼》片尾曲)", artist: "F.I.R.飞儿乐团" },
  { title: "第一次 (电视剧《白色恋曲》片尾曲)", artist: "光良" },
  { title: "暖暖 (电视剧《周末父母》片头曲)", artist: "梁静茹" },
  { title: "BINGBIAN病变 (女声版)", artist: "鞠文娴" },
  { title: "如果爱下去", artist: "张靓颖" },
  { title: "可爱女人", artist: "周杰伦" },
  { title: "天后 (电视剧《同伊》片尾曲)", artist: "陈势安" },
  { title: "王妃", artist: "萧敬腾" },
  { title: "囚鸟", artist: "张宇" },
  { title: "后来 (电视剧《真情》片尾曲)", artist: "刘若英" },
  { title: "勇气(电视剧《侠女闯天关》片尾曲)", artist: "梁静茹" },
  { title: "没那么简单", artist: "黄小琥" },
  { title: "多远都要在一起", artist: "G.E.M.邓紫棋" },
  { title: "演员", artist: "薛之谦" },
  // Set 3 (Previous additions)
  { title: "红玫瑰", artist: "陈奕迅" },
  { title: "如果这都不算爱", artist: "张学友" },
  { title: "倒带(电视剧《求婚事务所》片尾曲)", artist: "蔡依林" },
  { title: "吻别", artist: "张学友" },
  { title: "味道 (电视剧《滚石爱情故事》主题曲)", artist: "辛晓琪" },
  { title: "屋顶", artist: "周杰伦 / 温岚" },
  { title: "野孩子", artist: "杨千嬅" },
  { title: "一生所爱( 电影《大话西游之仙履奇缘》插曲)", artist: "卢冠廷 / Alison Lau" },
  { title: "伤痕(电视剧《滚石爱情故事》主题曲)", artist: "林忆莲" },
  { title: "旅行 (电影《后会无期》插曲)", artist: "许巍" },
  { title: "奉献(电视剧《夜市人生》插曲)", artist: "苏芮" },
  { title: "记得 (Remastered)", artist: "张惠妹" },
  { title: "温柔", artist: "五月天" },
  { title: "独家记忆", artist: "陈小春" },
  { title: "情书", artist: "张学友" },
  { title: "一眼万年(电视剧《爱情睡醒了》插曲)", artist: "林俊杰" }, // Image says Lin Junjie but original is SHE, trusting image/user
  { title: "记事本", artist: "金池" },
  { title: "哭不出来", artist: "迪克牛仔" },
  { title: "伤心太平洋 (电视剧《神雕侠侣(任贤齐版)》片尾曲)", artist: "任贤齐" },
  { title: "勇敢", artist: "BY2" },
  { title: "你怎么舍得我难过", artist: "黄品源" },
  { title: "背对背拥抱 (电视剧《爱情睡醒了》插曲)", artist: "林俊杰" },
  { title: "王子的新衣", artist: "萧敬腾" },
  { title: "宝贝对不起", artist: "草蜢" },
  { title: "等你爱我(电影《将爱情进行到底》片尾曲)", artist: "陈奕迅" },
  { title: "千年之恋", artist: "信乐团 / 戴爱玲" },
  { title: "此生不换 (电视剧《仙剑奇侠传3》插曲)", artist: "青鸟飞鱼" },
  { title: "偏爱", artist: "张芸京" },
  { title: "有何不可", artist: "许嵩" },
  { title: "夜空中最亮的星 (网络电影《摘星的你》主题曲)", artist: "逃跑计划" },
  { title: "认真的雪(电视剧《妈妈像花儿一样》插曲)", artist: "薛之谦" },
  { title: "曹操", artist: "林俊杰" },
  { title: "大城小爱", artist: "王力宏" },
  { title: "朋友(演奏版)", artist: "周华健" }, // Image says 演奏版? or just 朋友. Let's keep 朋友
  { title: "客官不可以", artist: "徐良 / 小凌" }
];
