// Large data pools for Migu Music playlists to ensure no duplicates
// Each pool corresponds to a specific playlist theme and count requirement

export const POOL_POP_HITS = [
  { title: "红色高跟鞋", artist: "蔡健雅" },
  { title: "会呼吸的痛", artist: "梁静茹" },
  { title: "背对背拥抱", artist: "林俊杰" },
  { title: "有形的翅膀", artist: "张韶涵" },
  { title: "越来越不懂", artist: "蔡健雅" },
  { title: "多远都要在一起", artist: "G.E.M.邓紫棋" },
  { title: "如果爱忘了", artist: "戚薇" },
  { title: "富士山下", artist: "陈奕迅" },
  { title: "句号", artist: "G.E.M.邓紫棋" },
  { title: "屋顶", artist: "周杰伦/温岚" },
  { title: "红颜", artist: "胡彦斌" },
  { title: "勇气", artist: "梁静茹" },
  { title: "偏爱", artist: "张芸京" },
  { title: "十年", artist: "陈奕迅" },
  { title: "绿光", artist: "孙燕姿" },
  { title: "失落沙洲", artist: "徐佳莹" },
  { title: "Where Did U Go", artist: "G.E.M.邓紫棋" },
  { title: "爱情转移", artist: "陈奕迅" },
  { title: "Letting Go", artist: "蔡健雅" },
  { title: "你要的全拿走", artist: "胡彦斌" },
  { title: "达尔文", artist: "林俊杰" },
  { title: "可惜没如果", artist: "林俊杰" },
  { title: "美人鱼", artist: "林俊杰" },
  { title: "淘汰", artist: "陈奕迅" },
  { title: "最佳损友", artist: "陈奕迅" },
  { title: "年轮", artist: "张碧晨" },
  { title: "孤独患者", artist: "陈奕迅" },
  { title: "猜不透", artist: "丁当" },
  { title: "倒带", artist: "蔡依林" },
  { title: "我知道", artist: "BY2" },
  { title: "爱不会绝迹", artist: "林俊杰" },
  { title: "到此为止", artist: "徐佳莹" },
  { title: "一样的月光", artist: "徐佳莹" },
  { title: "失语者", artist: "蔡健雅" },
  { title: "恶作剧", artist: "林依晨" },
  { title: "雨爱", artist: "杨丞琳" },
  { title: "还是会寂寞", artist: "陈绮贞" },
  { title: "匿名的好友", artist: "杨丞琳" },
  { title: "天空", artist: "蔡依林" },
  { title: "达尔文 II (进化版)", artist: "蔡健雅" },
  { title: "达尔文", artist: "蔡健雅" },
  { title: "冬眠", artist: "司南" },
  { title: "泡沫", artist: "G.E.M.邓紫棋" },
  { title: "江南", artist: "林俊杰" },
  { title: "下一个天亮", artist: "郭静" },
  { title: "倒数", artist: "G.E.M.邓紫棋" },
  { title: "写不完的温柔", artist: "G.E.M.邓紫棋" },
  { title: "喜欢你", artist: "G.E.M.邓紫棋" },
  { title: "来自天堂的魔鬼", artist: "G.E.M.邓紫棋" },
  { title: "再见", artist: "G.E.M.邓紫棋" },
  { title: "雨天", artist: "孙燕姿" },
  { title: "我怀念的", artist: "孙燕姿" },
  { title: "开始懂了", artist: "孙燕姿" },
  { title: "爱你", artist: "王心凌" },
  { title: "唯一", artist: "G.E.M.邓紫棋" },
  { title: "下一次爱情来的时候", artist: "蔡健雅" },
  { title: "情歌", artist: "梁静茹" },
  { title: "爱错", artist: "王力宏" },
  { title: "带我走", artist: "杨丞琳" },
  { title: "单车", artist: "陈奕迅" },
  { title: "遇见", artist: "孙燕姿" },
  { title: "遗失的心跳", artist: "萧亚轩" },
  { title: "当冬夜渐暖", artist: "孙燕姿" },
  { title: "一个人想着一个人", artist: "曾沛慈" },
  { title: "后来", artist: "刘若英" }
];

export const POOL_OLD_TIME_MALE = [
  { title: "十年", artist: "陈奕迅" }, { title: "童话", artist: "光良" }, { title: "简单爱", artist: "周杰伦" },
  { title: "江南", artist: "林俊杰" }, { title: "黄昏", artist: "周传雄" }, { title: "痴心绝对", artist: "李圣杰" },
  { title: "断点", artist: "张敬轩" }, { title: "七里香", artist: "周杰伦" }, { title: "老鼠爱大米", artist: "杨臣刚" },
  { title: "两只蝴蝶", artist: "庞龙" }, { title: "一生有你", artist: "水木年华" }, { title: "冲动的惩罚", artist: "刀郎" },
  { title: "曾经的你", artist: "许巍" }, { title: "有没有人告诉你", artist: "陈楚生" }, { title: "秋天不回来", artist: "王强" },
  { title: "求佛", artist: "誓言" }, { title: "那一夜", artist: "谢军" }, { title: "月亮之上", artist: "凤凰传奇" },
  { title: "认真的雪", artist: "薛之谦" }, { title: "该死的温柔", artist: "马天宇" }, { title: "有没有一首歌会让你想起我", artist: "周华健" },
  { title: "心太软", artist: "任贤齐" }, { title: "挪威的森林", artist: "伍佰" }, { title: "冰雨", artist: "刘德华" },
  { title: "忘情水", artist: "刘德华" }, { title: "吻别", artist: "张学友" }, { title: "一千个伤心的理由", artist: "张学友" },
  { title: "涛声依旧", artist: "毛宁" }, { title: "弯弯的月亮", artist: "刘欢" }, { title: "爱如潮水", artist: "张信哲" },
  { title: "过火", artist: "张信哲" }, { title: "信仰", artist: "张信哲" }, { title: "爱就一个字", artist: "张信哲" },
  { title: "白月光", artist: "张信哲" }, { title: "宽容", artist: "张信哲" }, { title: "别怕我伤心", artist: "张信哲" },
  { title: "有一点动心", artist: "张信哲" }, { title: "太想爱你", artist: "张信哲" }, { title: "从开始到现在", artist: "张信哲" }
];

export const POOL_NEW_VOICE = [
  { title: "星辰大海", artist: "黄霄雲" }, { title: "大风吹", artist: "王赫野" }, { title: "踏山河", artist: "七叔" },
  { title: "白月光与朱砂痣", artist: "大籽" }, { title: "千千万万", artist: "深海鱼子酱" }, { title: "沦陷", artist: "王靖雯" },
  { title: "善变", artist: "王靖雯" }, { title: "嘉宾", artist: "张远" }, { title: "还是分开", artist: "张叶蕾" },
  { title: "错位时空", artist: "艾辰" }, { title: "海底", artist: "一支白菊" }, { title: "不遗憾", artist: "李荣浩" },
  { title: "唯一", artist: "告五人" }, { title: "在这座城市遗失了你", artist: "告五人" }, { title: "爱人错过", artist: "告五人" },
  { title: "漠河舞厅", artist: "柳爽" }, { title: "秒针", artist: "阿梨粤" }, { title: "晚风心里吹", artist: "阿黎" },
  { title: "雾里", artist: "姚六一" }, { title: "骁", artist: "井胧" }, { title: "时光背面的我", artist: "刘至佳" },
  { title: "阿拉斯加海湾", artist: "蓝心羽" }, { title: "从前说", artist: "小阿七" }, { title: "就忘了吧", artist: "1K" },
  { title: "满天星辰不及你", artist: "ycccc" }, { title: "这世界那么多人", artist: "莫文蔚" }, { title: "如愿", artist: "王菲" },
  { title: "孤勇者", artist: "陈奕迅" }, { title: "人世间", artist: "雷佳" }, { title: "光亮", artist: "周深" },
  { title: "一路生花", artist: "温奕心" }, { title: "目及皆是你", artist: "小蓝背心" }, { title: "落日与晚风", artist: "IN-K/王忻辰" },
  { title: "若把你", artist: "Kirsty刘瑾睿" }, { title: "哪里都是你", artist: "队长" }, { title: "予你", artist: "队长" },
  { title: "NUNA", artist: "队长" }, { title: "11", artist: "队长/黄礼格" }, { title: "好想爱这个世界啊", artist: "华晨宇" },
  { title: "你要相信这不是最后一天", artist: "华晨宇" }, { title: "斗牛", artist: "华晨宇" }, { title: "七重人格", artist: "华晨宇" }
];

export const POOL_RB = [
  { title: "爱很简单", artist: "陶喆" }, { title: "普通朋友", artist: "陶喆" }, { title: "流沙", artist: "陶喆" },
  { title: "飞机场的10:30", artist: "陶喆" }, { title: "黑色幽默", artist: "周杰伦" }, { title: "龙卷风", artist: "周杰伦" },
  { title: "爱在西元前", artist: "周杰伦" }, { title: "唯一", artist: "王力宏" }, { title: "心中的日月", artist: "王力宏" },
  { title: "大城小爱", artist: "王力宏" }, { title: "Kiss Goodbye", artist: "王力宏" }, { title: "Love Song", artist: "方大同" },
  { title: "三人游", artist: "方大同" }, { title: "红豆", artist: "方大同" }, { title: "特别的人", artist: "方大同" },
  { title: "模特", artist: "李荣浩" }, { title: "李白", artist: "李荣浩" }, { title: "不将就", artist: "李荣浩" },
  { title: "戒烟", artist: "李荣浩" }, { title: "年少有为", artist: "李荣浩" }, { title: "月光", artist: "胡彦斌" },
  { title: "红颜", artist: "胡彦斌" }, { title: "男人KTV", artist: "胡彦斌" }, { title: "专属天使", artist: "Tank" },
  { title: "三国恋", artist: "Tank" }, { title: "如果我变成回忆", artist: "Tank" }, { title: "不得不爱", artist: "潘玮柏" },
  { title: "快乐崇拜", artist: "潘玮柏" }, { title: "壁虎漫步", artist: "潘玮柏" }, { title: "反转地球", artist: "潘玮柏" },
  { title: "天天", artist: "陶喆" }, { title: "Melody", artist: "陶喆" }, { title: "寂寞的季节", artist: "陶喆" },
  { title: "可爱女人", artist: "周杰伦" }, { title: "星晴", artist: "周杰伦" }, { title: "娘子", artist: "周杰伦" },
  { title: "公公偏头痛", artist: "周杰伦" }, { title: "迷迭香", artist: "周杰伦" }, { title: "花田错", artist: "王力宏" },
  { title: "盖世英雄", artist: "王力宏" }, { title: "春雨里洗过的太阳", artist: "王力宏" }, { title: "需要人陪", artist: "王力宏" },
  { title: "苏丽珍", artist: "方大同" }, { title: "春风吹", artist: "方大同" }, { title: "南音", artist: "方大同" },
  { title: "好不容易", artist: "方大同" }, { title: "喜剧之王", artist: "李荣浩" }, { title: "作曲家", artist: "李荣浩" },
  { title: "老街", artist: "李荣浩" }, { title: "爸爸妈妈", artist: "李荣浩" }, { title: "麻雀", artist: "李荣浩" },
  { title: "诀别诗", artist: "胡彦斌" }, { title: "你要的全拿走", artist: "胡彦斌" }, { title: "潇洒小姐", artist: "萧亚轩" },
  { title: "表白", artist: "萧亚轩" }, { title: "爱的主打歌", artist: "萧亚轩" }, { title: "突然想起你", artist: "萧亚轩" },
  { title: "小宇", artist: "张震岳" }, { title: "爱我别走", artist: "张震岳" }, { title: "思念是一种病", artist: "张震岳" },
  { title: "再见", artist: "张震岳" }, { title: "路口", artist: "张震岳" }, { title: "小镇姑娘", artist: "陶喆" },
  { title: "沙滩", artist: "陶喆" }, { title: "找自己", artist: "陶喆" }, { title: "黑色柳丁", artist: "陶喆" },
  { title: "Angel", artist: "陶喆" }, { title: "Susan说", artist: "陶喆" }, { title: "就是爱你", artist: "陶喆" }
];

export const POOL_CLASSIC = [
  { title: "甜蜜蜜", artist: "邓丽君" }, { title: "月亮代表我的心", artist: "邓丽君" }, { title: "小城故事", artist: "邓丽君" },
  { title: "我只在乎你", artist: "邓丽君" }, { title: "漫步人生路", artist: "邓丽君" }, { title: "吻别", artist: "张学友" },
  { title: "一千个伤心的理由", artist: "张学友" }, { title: "只想一生跟你走", artist: "张学友" }, { title: "祝福", artist: "张学友" },
  { title: "饿狼传说", artist: "张学友" }, { title: "被遗忘的时光", artist: "蔡琴" }, { title: "恰似你的温柔", artist: "蔡琴" },
  { title: "你的眼神", artist: "蔡琴" }, { title: "渡口", artist: "蔡琴" }, { title: "一剪梅", artist: "费玉清" },
  { title: "千里之外", artist: "费玉清" }, { title: "梦驼铃", artist: "费玉清" }, { title: "童年", artist: "罗大佑" },
  { title: "光阴的故事", artist: "罗大佑" }, { title: "恋曲1990", artist: "罗大佑" }, { title: "山丘", artist: "李宗盛" },
  { title: "凡人歌", artist: "李宗盛" }, { title: "鬼迷心窍", artist: "李宗盛" }, { title: "给自己的歌", artist: "李宗盛" },
  { title: "讲不出再见", artist: "谭咏麟" }, { title: "朋友", artist: "谭咏麟" }, { title: "水中花", artist: "谭咏麟" },
  { title: "一生中最爱", artist: "谭咏麟" }, { title: "女人花", artist: "梅艳芳" }, { title: "夕阳之歌", artist: "梅艳芳" },
  { title: "亲密爱人", artist: "梅艳芳" }, { title: "一生爱你千百回", artist: "梅艳芳" }, { title: "我", artist: "张国荣" },
  { title: "风继续吹", artist: "张国荣" }, { title: "当年情", artist: "张国荣" }, { title: "倩女幽魂", artist: "张国荣" },
  { title: "沉默是金", artist: "张国荣" }, { title: "男儿当自强", artist: "林子祥" }, { title: "分分钟需要你", artist: "林子祥" },
  { title: "数字人生", artist: "林子祥" }, { title: "上海滩", artist: "叶丽仪" }, { title: "万水千山总是情", artist: "汪明荃" },
  { title: "铁血丹心", artist: "罗文/甄妮" }, { title: "世间始终你好", artist: "罗文/甄妮" }, { title: "偏偏喜欢你", artist: "陈百强" },
  { title: "一生何求", artist: "陈百强" }, { title: "红日", artist: "李克勤" }, { title: "月半小夜曲", artist: "李克勤" },
  { title: "护花使者", artist: "李克勤" }, { title: "千千阙歌", artist: "陈慧娴" }, { title: "飘雪", artist: "陈慧娴" },
  { title: "人生何处不相逢", artist: "陈慧娴" }, { title: "容易受伤的女人", artist: "王菲" }, { title: "执迷不悔", artist: "王菲" },
  { title: "红豆", artist: "王菲" }, { title: "潇洒走一回", artist: "叶倩文" }, { title: "祝福", artist: "叶倩文" },
  { title: "情人知己", artist: "叶倩文" }, { title: "真心英雄", artist: "成龙/周华健/李宗盛" }, { title: "朋友", artist: "周华健" },
  { title: "花心", artist: "周华健" }, { title: "刀剑如梦", artist: "周华健" }, { title: "难念的经", artist: "周华健" },
  { title: "爱相随", artist: "周华健" }, { title: "让我欢喜让我忧", artist: "周华健" }, { title: "风雨无阻", artist: "周华健" },
  { title: "水手", artist: "郑智化" }, { title: "星星点灯", artist: "郑智化" }, { title: "大海", artist: "张雨生" },
  { title: "我的未来不是梦", artist: "张雨生" }, { title: "口是心非", artist: "张雨生" }, { title: "挪威的森林", artist: "伍佰" },
  { title: "突然的自我", artist: "伍佰" }, { title: "浪人情歌", artist: "伍佰" }, { title: "Last Dance", artist: "伍佰" },
  { title: "爱上一个不回家的人", artist: "林忆莲" }, { title: "至少还有你", artist: "林忆莲" }, { title: "当爱已成往事", artist: "林忆莲" },
  { title: "伤痕", artist: "林忆莲" }, { title: "听说爱情回来过", artist: "林忆莲" }, { title: "特别的爱给特别的你", artist: "伍思凯" },
  { title: "用心良苦", artist: "张宇" }, { title: "月亮惹的祸", artist: "张宇" }, { title: "雨一直下", artist: "张宇" },
  { title: "一言难尽", artist: "张宇" }, { title: "过火", artist: "张信哲" }, { title: "爱如潮水", artist: "张信哲" },
  { title: "信仰", artist: "张信哲" }, { title: "爱就一个字", artist: "张信哲" }, { title: "白月光", artist: "张信哲" },
  { title: "宽容", artist: "张信哲" }, { title: "别怕我伤心", artist: "张信哲" }, { title: "有一点动心", artist: "张信哲" },
  { title: "太想爱你", artist: "张信哲" }, { title: "从开始到现在", artist: "张信哲" }, { title: "忘情水", artist: "刘德华" },
  { title: "冰雨", artist: "刘德华" }, { title: "练习", artist: "刘德华" }, { title: "笨小孩", artist: "刘德华" },
  { title: "男人哭吧不是罪", artist: "刘德华" }, { title: "爱你一万年", artist: "刘德华" }, { title: "今天", artist: "刘德华" },
  { title: "世界第一等", artist: "刘德华" }, { title: "恭喜发财", artist: "刘德华" }, { title: "一起走过的日子", artist: "刘德华" },
  { title: "暗里着迷", artist: "刘德华" }, { title: "谢谢你的爱", artist: "刘德华" }, { title: "天意", artist: "刘德华" },
  { title: "中国人", artist: "刘德华" }, { title: "来生缘", artist: "刘德华" }, { title: "如果有一天", artist: "刘德华" },
  { title: "孤星泪", artist: "刘德华" }, { title: "真永远", artist: "刘德华" }, { title: "相思成灾", artist: "刘德华" },
  { title: "无心睡眠", artist: "张国荣" }, { title: "Monica", artist: "张国荣" }, { title: "侧面", artist: "张国荣" },
  { title: "有谁共鸣", artist: "张国荣" }, { title: "拒绝再玩", artist: "张国荣" }, { title: "暴风一族", artist: "张国荣" },
  { title: "追", artist: "张国荣" }, { title: "今生今世", artist: "张国荣" }, { title: "当爱已成往事", artist: "张国荣" },
  { title: "夜半歌声", artist: "张国荣" }, { title: "深情相拥", artist: "张国荣" }, { title: "明星", artist: "张国荣" }
];

export const POOL_BANDS = [
  { title: "海阔天空", artist: "Beyond" }, { title: "光辉岁月", artist: "Beyond" }, { title: "真的爱你", artist: "Beyond" },
  { title: "喜欢你", artist: "Beyond" }, { title: "不再犹豫", artist: "Beyond" }, { title: "大地", artist: "Beyond" },
  { title: "冷雨夜", artist: "Beyond" }, { title: "情人", artist: "Beyond" }, { title: "Amani", artist: "Beyond" },
  { title: "倔强", artist: "五月天" }, { title: "温柔", artist: "五月天" }, { title: "突然好想你", artist: "五月天" },
  { title: "知足", artist: "五月天" }, { title: "恋爱ing", artist: "五月天" }, { title: "离开地球表面", artist: "五月天" },
  { title: "伤心的人别听慢歌", artist: "五月天" }, { title: "无与伦比的美丽", artist: "苏打绿" }, { title: "小情歌", artist: "苏打绿" },
  { title: "好想去海边", artist: "夏日入侵企画" }, { title: "极恶都市", artist: "夏日入侵企画" }, { title: "想去海边", artist: "夏日入侵企画" },
  { title: "你要跳舞吗", artist: "新裤子" }, { title: "没有理想的人不伤心", artist: "新裤子" }, { title: "生活因你而火热", artist: "新裤子" },
  { title: "艾瑞巴迪", artist: "新裤子" }, { title: "公路之歌", artist: "痛仰" }, { title: "再见杰克", artist: "痛仰" },
  { title: "西湖", artist: "痛仰" }, { title: "杀死那个石家庄人", artist: "万能青年旅店" }, { title: "十万嬉皮", artist: "万能青年旅店" },
  { title: "秦皇岛", artist: "万能青年旅店" }, { title: "追梦赤子心", artist: "GALA" }, { title: "Young For You", artist: "GALA" },
  { title: "夜空中最亮的星", artist: "逃跑计划" }, { title: "一万次悲伤", artist: "逃跑计划" }, { title: "火车驶向云外", artist: "刺猬" },
  { title: "大风吹", artist: "草东没有派对" }, { title: "山海", artist: "草东没有派对" }, { title: "烂泥", artist: "草东没有派对" },
  { title: "鲜花", artist: "重塑雕像的权利" }, { title: "Hallelujah", artist: "重塑雕像的权利" }, { title: "霓虹甜心", artist: "马赛克" },
  { title: "New Boy", artist: "盘尼西林" }, { title: "再见", artist: "盘尼西林" }, { title: "雨夜曼彻斯特", artist: "盘尼西林" },
  { title: "Last Dance", artist: "伍佰 & China Blue" }, { title: "挪威的森林", artist: "伍佰 & China Blue" }, { title: "浪人情歌", artist: "伍佰 & China Blue" },
  { title: "浪子回头", artist: "茄子蛋" }, { title: "浪流连", artist: "茄子蛋" }, { title: "爱情你比我想的阁楼", artist: "茄子蛋" },
  { title: "想见你想见你想见你", artist: "八三夭" }, { title: "最后的831", artist: "八三夭" }, { title: "东区东区", artist: "八三夭" },
  { title: "你的答案", artist: "阿冗" }, { title: "世界这么大还是遇见你", artist: "程响" }, { title: "少年", artist: "梦然" },
  { title: "起风了", artist: "买辣椒也用券" }, { title: "绿色", artist: "陈雪凝" }, { title: "你的酒馆对我打了烊", artist: "陈雪凝" },
  { title: "我记得", artist: "赵雷" }, { title: "我们的时光", artist: "赵雷" }, { title: "再见", artist: "张震岳" },
  { title: "路口", artist: "张震岳" }, { title: "思念是一种病", artist: "张震岳" }, { title: "爱我别走", artist: "张震岳" },
  { title: "小宇", artist: "张震岳" }, { title: "自由", artist: "张震岳" }, { title: "爱的初体验", artist: "张震岳" },
  { title: "抱着你", artist: "张震岳" }, { title: "再见", artist: "张震岳" }, { title: "别来纠缠我", artist: "黑豹乐队" },
  { title: "无地自容", artist: "黑豹乐队" }, { title: "Don't Break My Heart", artist: "黑豹乐队" }, { title: "梦回唐朝", artist: "唐朝乐队" },
  { title: "国际歌", artist: "唐朝乐队" }, { title: "飞翔鸟", artist: "唐朝乐队" }, { title: "太阳", artist: "唐朝乐队" },
  { title: "赤裸裸", artist: "郑钧" }, { title: "灰姑娘", artist: "郑钧" }, { title: "回到拉萨", artist: "郑钧" },
  { title: "私奔", artist: "郑钧" }, { title: "长安长安", artist: "郑钧" }, { title: "怒放的生命", artist: "汪峰" },
  { title: "春天里", artist: "汪峰" }, { title: "北京北京", artist: "汪峰" }, { title: "存在", artist: "汪峰" }
];

export const POOL_FOLK = [
  { title: "成都", artist: "赵雷" }, { title: "南方姑娘", artist: "赵雷" }, { title: "画", artist: "赵雷" },
  { title: "少年锦时", artist: "赵雷" }, { title: "理想", artist: "赵雷" }, { title: "三十岁的女人", artist: "赵雷" },
  { title: "安和桥", artist: "宋冬野" }, { title: "董小姐", artist: "宋冬野" }, { title: "斑马，斑马", artist: "宋冬野" },
  { title: "莉莉安", artist: "宋冬野" }, { title: "鸽子", artist: "宋冬野" }, { title: "南山南", artist: "马頔" },
  { title: "傲寒", artist: "马頔" }, { title: "奇妙能力歌", artist: "陈粒" }, { title: "小半", artist: "陈粒" },
  { title: "走马", artist: "陈粒" }, { title: "易燃易爆炸", artist: "陈粒" }, { title: "历历万乡", artist: "陈粒" },
  { title: "平凡之路", artist: "朴树" }, { title: "那些花儿", artist: "朴树" }, { title: "生如夏花", artist: "朴树" },
  { title: "白桦林", artist: "朴树" }, { title: "New Boy", artist: "朴树" }, { title: "同桌的你", artist: "老狼" },
  { title: "睡在我上铺的兄弟", artist: "老狼" }, { title: "蓝莲花", artist: "许巍" }, { title: "曾经的你", artist: "许巍" },
  { title: "像风一样自由", artist: "许巍" }, { title: "故乡", artist: "许巍" }, { title: "旅行", artist: "许巍" },
  { title: "米店", artist: "张玮玮" }, { title: "北方女王", artist: "尧十三" }, { title: "他妈的", artist: "尧十三" },
  { title: "瞎子", artist: "尧十三" }, { title: "理想三旬", artist: "陈鸿宇" }, { title: "一如年少模样", artist: "陈鸿宇" },
  { title: "行歌", artist: "陈鸿宇" }, { title: "春风十里", artist: "鹿先森乐队" }, { title: "七月上", artist: "Jam" },
  { title: "差三岁", artist: "Jam" }, { title: "借", artist: "毛不易" }, { title: "消愁", artist: "毛不易" },
  { title: "像我这样的人", artist: "毛不易" }, { title: "一荤一素", artist: "毛不易" }, { title: "无问", artist: "毛不易" },
  { title: "平凡的一天", artist: "毛不易" }, { title: "牧马城市", artist: "毛不易" }, { title: "东北民谣", artist: "毛不易" },
  { title: "二零三", artist: "毛不易" }, { title: "深夜一角", artist: "毛不易" }, { title: "小王", artist: "毛不易" },
  { title: "儿时", artist: "刘昊霖" }, { title: "玫瑰", artist: "贰佰" }, { title: "狗日的青春", artist: "贰佰" },
  { title: "在这个世界相遇", artist: "陈奕迅" }, { title: "陪你度过漫长岁月", artist: "陈奕迅" }, { title: "去大理", artist: "郝云" },
  { title: "活着", artist: "郝云" }, { title: "结了", artist: "郝云" }, { title: "突然想到理想这个词", artist: "郝云" },
  { title: "如果有来生", artist: "谭维维" }, { title: "乌兰巴托的夜", artist: "谭维维" }, { title: "往后余生", artist: "马良" }
];

export const POOL_KTV = [
  { title: "十年", artist: "陈奕迅" }, { title: "K歌之王", artist: "陈奕迅" }, { title: "浮夸", artist: "陈奕迅" },
  { title: "单车", artist: "陈奕迅" }, { title: "好久不见", artist: "陈奕迅" }, { title: "爱情转移", artist: "陈奕迅" },
  { title: "富士山下", artist: "陈奕迅" }, { title: "告白气球", artist: "周杰伦" }, { title: "晴天", artist: "周杰伦" },
  { title: "稻香", artist: "周杰伦" }, { title: "青花瓷", artist: "周杰伦" }, { title: "搁浅", artist: "周杰伦" },
  { title: "一路向北", artist: "周杰伦" }, { title: "说好的幸福呢", artist: "周杰伦" }, { title: "算什么男人", artist: "周杰伦" },
  { title: "江南", artist: "林俊杰" }, { title: "修炼爱情", artist: "林俊杰" }, { title: "可惜没如果", artist: "林俊杰" },
  { title: "小酒窝", artist: "林俊杰/蔡卓妍" }, { title: "背对背拥抱", artist: "林俊杰" }, { title: "一千年以后", artist: "林俊杰" },
  { title: "曹操", artist: "林俊杰" }, { title: "听海", artist: "张惠妹" }, { title: "记得", artist: "张惠妹" },
  { title: "我可以抱你吗", artist: "张惠妹" }, { title: "趁早", artist: "张惠妹" }, { title: "人质", artist: "张惠妹" },
  { title: "解脱", artist: "张惠妹" }, { title: "倔强", artist: "五月天" }, { title: "突然好想你", artist: "五月天" },
  { title: "知足", artist: "五月天" }, { title: "温柔", artist: "五月天" }, { title: "拥抱", artist: "五月天" },
  { title: "日不落", artist: "蔡依林" }, { title: "倒带", artist: "蔡依林" }, { title: "舞娘", artist: "蔡依林" },
  { title: "绿光", artist: "孙燕姿" }, { title: "开始懂了", artist: "孙燕姿" }, { title: "遇见", artist: "孙燕姿" },
  { title: "我怀念的", artist: "孙燕姿" }, { title: "天黑黑", artist: "孙燕姿" }, { title: "红豆", artist: "王菲" },
  { title: "因为爱情", artist: "王菲/陈奕迅" }, { title: "匆匆那年", artist: "王菲" }, { title: "传奇", artist: "王菲" },
  { title: "海阔天空", artist: "Beyond" }, { title: "光辉岁月", artist: "Beyond" }, { title: "喜欢你", artist: "Beyond" },
  { title: "吻别", artist: "张学友" }, { title: "一千个伤心的理由", artist: "张学友" }, { title: "心如刀割", artist: "张学友" },
  { title: "后来", artist: "刘若英" }, { title: "成全", artist: "刘若英" }, { title: "很爱很爱你", artist: "刘若英" },
  { title: "泡沫", artist: "G.E.M.邓紫棋" }, { title: "光年之外", artist: "G.E.M.邓紫棋" }, { title: "倒数", artist: "G.E.M.邓紫棋" },
  { title: "句号", artist: "G.E.M.邓紫棋" }, { title: "来自天堂的魔鬼", artist: "G.E.M.邓紫棋" }, { title: "多远都要在一起", artist: "G.E.M.邓紫棋" },
  { title: "倒带", artist: "蔡依林" }, { title: "听说爱情回来过", artist: "蔡依林" }, { title: "柠檬草的味道", artist: "蔡依林" },
  { title: "说爱你", artist: "蔡依林" }, { title: "布拉格广场", artist: "蔡依林" }, { title: "野子", artist: "苏运莹" },
  { title: "凉凉", artist: "张碧晨/杨宗纬" }, { title: "年轮", artist: "张碧晨" }, { title: "开往早晨的午夜", artist: "张碧晨" },
  { title: "曾经", artist: "张碧晨" }, { title: "胡桃夹子", artist: "张碧晨" }, { title: "演员", artist: "薛之谦" },
  { title: "丑八怪", artist: "薛之谦" }, { title: "绅士", artist: "薛之谦" }, { title: "认真的雪", artist: "薛之谦" },
  { title: "刚刚好", artist: "薛之谦" }, { title: "天外来物", artist: "薛之谦" }, { title: "你还要我怎样", artist: "薛之谦" },
  { title: "消愁", artist: "毛不易" }, { title: "像我这样的人", artist: "毛不易" }, { title: "一荤一素", artist: "毛不易" },
  { title: "不染", artist: "毛不易" }, { title: "无问", artist: "毛不易" }, { title: "盛夏", artist: "毛不易" },
  { title: "平凡的一天", artist: "毛不易" }, { title: "借", artist: "毛不易" }, { title: "如果有一天我变得很有钱", artist: "毛不易" },
  { title: "感觉自己是巨星", artist: "毛不易" }, { title: "哎哟", artist: "毛不易" }, { title: "小王", artist: "毛不易" },
  { title: "深夜一角", artist: "毛不易" }, { title: "水乡", artist: "毛不易" }, { title: "一程山路", artist: "毛不易" },
  { title: "二零三", artist: "毛不易" }, { title: "东北民谣", artist: "毛不易" }, { title: "呓语", artist: "毛不易" },
  { title: "等", artist: "毛不易" }, { title: "芬芳一生", artist: "毛不易" }, { title: "在此山中", artist: "毛不易" },
  { title: "给你给我", artist: "毛不易" }, { title: "城市傍晚", artist: "毛不易" }, { title: "纯净无比", artist: "毛不易" },
  { title: "海上日记", artist: "毛不易" }, { title: "爱很美味", artist: "毛不易" }, { title: "旅行家说", artist: "毛不易" },
  { title: "于是没有洗头", artist: "毛不易" }, { title: "幼鸟指南", artist: "毛不易" }, { title: "缝隙之人", artist: "毛不易" },
  { title: "孤独患者", artist: "陈奕迅" }, { title: "红玫瑰", artist: "陈奕迅" }, { title: "不要说话", artist: "陈奕迅" },
  { title: "陪你度过漫长岁月", artist: "陈奕迅" }, { title: "我们", artist: "陈奕迅" }, { title: "阴天", artist: "莫文蔚" },
  { title: "盛夏的果实", artist: "莫文蔚" }, { title: "忽然之间", artist: "莫文蔚" }, { title: "如果没有你", artist: "莫文蔚" },
  { title: "电台情歌", artist: "莫文蔚" }, { title: "广岛之恋", artist: "莫文蔚/张洪量" }, { title: "他不爱我", artist: "莫文蔚" },
  { title: "独角戏", artist: "许茹芸" }, { title: "如果云知道", artist: "许茹芸" }, { title: "泪海", artist: "许茹芸" },
  { title: "日光机场", artist: "许茹芸" }, { title: "好听", artist: "许茹芸" }, { title: "值得", artist: "郑秀文" },
  { title: "出界", artist: "郑秀文" }, { title: "眉飞色舞", artist: "郑秀文" }, { title: "终身美丽", artist: "郑秀文" },
  { title: "短发", artist: "梁咏琪" }, { title: "胆小鬼", artist: "梁咏琪" }, { title: "花火", artist: "梁咏琪" },
  { title: "中意他", artist: "梁咏琪" }, { title: "爱的代价", artist: "张艾嘉" }, { title: "童年", artist: "张艾嘉" },
  { title: "光阴的故事", artist: "张艾嘉" }, { title: "忙与盲", artist: "张艾嘉" }, { title: "最爱", artist: "张艾嘉" },
  { title: "梦醒时分", artist: "陈淑桦" }, { title: "问", artist: "陈淑桦" }, { title: "滚滚红尘", artist: "陈淑桦" }
];

export const POOL_WESTERN = [
  { title: "Love Story", artist: "Taylor Swift" }, { title: "You Belong With Me", artist: "Taylor Swift" }, { title: "Blank Space", artist: "Taylor Swift" },
  { title: "Shake It Off", artist: "Taylor Swift" }, { title: "Lover", artist: "Taylor Swift" }, { title: "Cruel Summer", artist: "Taylor Swift" },
  { title: "Anti-Hero", artist: "Taylor Swift" }, { title: "Baby", artist: "Justin Bieber" }, { title: "Sorry", artist: "Justin Bieber" },
  { title: "Love Yourself", artist: "Justin Bieber" }, { title: "Stay", artist: "The Kid LAROI/Justin Bieber" }, { title: "Peaches", artist: "Justin Bieber" },
  { title: "Someone Like You", artist: "Adele" }, { title: "Rolling in the Deep", artist: "Adele" }, { title: "Hello", artist: "Adele" },
  { title: "Easy On Me", artist: "Adele" }, { title: "Set Fire to the Rain", artist: "Adele" }, { title: "Shape of You", artist: "Ed Sheeran" },
  { title: "Perfect", artist: "Ed Sheeran" }, { title: "Thinking Out Loud", artist: "Ed Sheeran" }, { title: "Photograph", artist: "Ed Sheeran" },
  { title: "Bad Habits", artist: "Ed Sheeran" }, { title: "Shivers", artist: "Ed Sheeran" }, { title: "Uptown Funk", artist: "Bruno Mars" },
  { title: "Just the Way You Are", artist: "Bruno Mars" }, { title: "The Lazy Song", artist: "Bruno Mars" }, { title: "Grenade", artist: "Bruno Mars" },
  { title: "24K Magic", artist: "Bruno Mars" }, { title: "Leave The Door Open", artist: "Silk Sonic" }, { title: "Sugar", artist: "Maroon 5" },
  { title: "Moves Like Jagger", artist: "Maroon 5" }, { title: "Payphone", artist: "Maroon 5" }, { title: "Memories", artist: "Maroon 5" },
  { title: "Girls Like You", artist: "Maroon 5" }, { title: "7 rings", artist: "Ariana Grande" }, { title: "thank u, next", artist: "Ariana Grande" },
  { title: "Side To Side", artist: "Ariana Grande" }, { title: "Positions", artist: "Ariana Grande" }, { title: "Yellow", artist: "Coldplay" },
  { title: "Viva La Vida", artist: "Coldplay" }, { title: "Fix You", artist: "Coldplay" }, { title: "Something Just Like This", artist: "The Chainsmokers/Coldplay" },
  { title: "A Sky Full of Stars", artist: "Coldplay" }, { title: "Paradise", artist: "Coldplay" }, { title: "Hymn for the Weekend", artist: "Coldplay" },
  { title: "We Don't Talk Anymore", artist: "Charlie Puth" }, { title: "Attention", artist: "Charlie Puth" }, { title: "See You Again", artist: "Wiz Khalifa/Charlie Puth" },
  { title: "Senorita", artist: "Shawn Mendes/Camila Cabello" }, { title: "Havana", artist: "Camila Cabello" }, { title: "Bad Guy", artist: "Billie Eilish" },
  { title: "Lovely", artist: "Billie Eilish" }, { title: "Ocean Eyes", artist: "Billie Eilish" }, { title: "Happier Than Ever", artist: "Billie Eilish" },
  { title: "Blinding Lights", artist: "The Weeknd" }, { title: "Save Your Tears", artist: "The Weeknd" }, { title: "Starboy", artist: "The Weeknd" },
  { title: "Die For You", artist: "The Weeknd" }, { title: "Levitating", artist: "Dua Lipa" }, { title: "Don't Start Now", artist: "Dua Lipa" },
  { title: "New Rules", artist: "Dua Lipa" }, { title: "Dance Monkey", artist: "Tones and I" }, { title: "Believer", artist: "Imagine Dragons" },
  { title: "Demons", artist: "Imagine Dragons" }, { title: "Radioactive", artist: "Imagine Dragons" }, { title: "Thunder", artist: "Imagine Dragons" },
  { title: "Counting Stars", artist: "OneRepublic" }, { title: "Apologize", artist: "OneRepublic" }, { title: "Secrets", artist: "OneRepublic" },
  { title: "Closer", artist: "The Chainsmokers" }, { title: "Paris", artist: "The Chainsmokers" }, { title: "Don't Let Me Down", artist: "The Chainsmokers" },
  { title: "Faded", artist: "Alan Walker" }, { title: "Alone", artist: "Alan Walker" }, { title: "The Spectre", artist: "Alan Walker" }
];

export const POOL_DOUYIN = [
  { title: "飞鸟和蝉", artist: "任然" }, { title: "与我无关", artist: "阿冗" }, { title: "白月光与朱砂痣", artist: "大籽" },
  { title: "踏山河", artist: "是七叔呢" }, { title: "大风吹", artist: "王赫野" }, { title: "下山", artist: "要不要买菜" },
  { title: "丢了你", artist: "井胧" }, { title: "海市蜃楼", artist: "三叔说" }, { title: "热爱105°C的你", artist: "阿肆" },
  { title: "少年", artist: "梦然" }, { title: "世界这么大还是遇见你", artist: "程响" }, { title: "惊雷", artist: "皮卡丘多多" },
  { title: "你的答案", artist: "阿冗" }, { title: "绿色", artist: "陈雪凝" }, { title: "你的酒馆对我打了烊", artist: "陈雪凝" },
  { title: "野狼Disco", artist: "宝石Gem" }, { title: "芒种", artist: "音阙诗听" }, { title: "无价之姐", artist: "李宇春" },
  { title: "微微", artist: "傅如乔" }, { title: "燕无歇", artist: "是七叔呢" }, { title: "醒不来的梦", artist: "回小仙" },
  { title: "笑纳", artist: "花僮" }, { title: "不过人间", artist: "海来阿木" }, { title: "点歌的人", artist: "海来阿木" },
  { title: "你的万水千山", artist: "海来阿木" }, { title: "别知己", artist: "海来阿木" }, { title: "西楼别序", artist: "尹昔眠" },
  { title: "落在生命里的光", artist: "尹昔眠" }, { title: "错位时空", artist: "艾辰" }, { title: "星辰大海", artist: "黄霄雲" },
  { title: "千千万万", artist: "深海鱼子酱" }, { title: "善变", artist: "王靖雯" }, { title: "沦陷", artist: "王靖雯" },
  { title: "讨", artist: "王靖雯" }, { title: "忘了没有", artist: "王靖雯" }, { title: "嘉宾", artist: "张远" },
  { title: "还是分开", artist: "张叶蕾" }, { title: "就忘了吧", artist: "1K" }, { title: "满天星辰不及你", artist: "ycccc" },
  { title: "从前说", artist: "小阿七" }, { title: "时光背面的我", artist: "刘至佳" }, { title: "阿拉斯加海湾", artist: "蓝心羽" },
  { title: "雾里", artist: "姚六一" }, { title: "骁", artist: "井胧/井迪" }, { title: "目及皆是你", artist: "小蓝背心" },
  { title: "Ring Ring Ring", artist: "S.H.E" }, { title: "Super Star", artist: "S.H.E" }, { title: "不想长大", artist: "S.H.E" },
  { title: "中国话", artist: "S.H.E" }, { title: "波斯猫", artist: "S.H.E" }, { title: "痛快", artist: "S.H.E" },
  { title: "SHERO", artist: "S.H.E" }, { title: "触电", artist: "S.H.E" }, { title: "热带雨林", artist: "S.H.E" },
  { title: "半糖主义", artist: "S.H.E" }, { title: "恋人未满", artist: "S.H.E" }, { title: "天灰", artist: "S.H.E" },
  { title: "五月天", artist: "S.H.E" }, { title: "一眼万年", artist: "S.H.E" }, { title: "美丽新世界", artist: "S.H.E" },
  { title: "候鸟", artist: "S.H.E" }, { title: "他还是不懂", artist: "S.H.E" }, { title: "老婆", artist: "S.H.E" },
  { title: "爱我的资格", artist: "S.H.E" }, { title: "心还是热的", artist: "S.H.E" }, { title: "你曾是少年", artist: "S.H.E" },
  { title: "十七", artist: "S.H.E" }, { title: "花又开好了", artist: "S.H.E" }, { title: "听袁惟仁弹吉他", artist: "S.H.E" },
  { title: "怎么办", artist: "S.H.E" }, { title: "我爱你", artist: "S.H.E" }, { title: "远方", artist: "S.H.E" },
  { title: "河滨公园", artist: "S.H.E" }, { title: "落大雨", artist: "S.H.E" }, { title: "安全感", artist: "S.H.E" },
  { title: "月桂女神", artist: "S.H.E" }, { title: "绿洲", artist: "S.H.E" }, { title: "长相思", artist: "S.H.E" },
  { title: "斗牛士之歌", artist: "S.H.E" }, { title: "借口", artist: "S.H.E" }, { title: "Boom", artist: "S.H.E" },
  { title: "宇宙小姐", artist: "S.H.E" }, { title: "沿海公路的出口", artist: "S.H.E" }, { title: "天亮了", artist: "S.H.E" },
  { title: "女孩当自强", artist: "S.H.E" }, { title: "我是火星人", artist: "S.H.E" }, { title: "612星球", artist: "S.H.E" },
  { title: "店小二", artist: "S.H.E" }, { title: "锁住时间", artist: "S.H.E" }, { title: "可爱万岁", artist: "S.H.E" },
  { title: "梦田", artist: "S.H.E" }, { title: "最近还好吗", artist: "S.H.E" }, { title: "爱上你", artist: "S.H.E" },
  { title: "你说", artist: "S.H.E" }, { title: "收留我", artist: "S.H.E" }, { title: "两个人的荒岛", artist: "S.H.E" },
  { title: "少了一个人", artist: "S.H.E" }, { title: "有没有", artist: "S.H.E" }, { title: "如果我变成回忆", artist: "Tank" },
  { title: "专属天使", artist: "Tank" }, { title: "三国恋", artist: "Tank" }, { title: "千年泪", artist: "Tank" },
  { title: "非你莫属", artist: "Tank" }, { title: "会长大的幸福", artist: "Tank" }, { title: "城里的月光", artist: "Tank" },
  { title: "全世界都停电", artist: "Tank" }, { title: "岚", artist: "Tank" }, { title: "斗牛", artist: "Tank" },
  { title: "街头霸王", artist: "Tank" }, { title: "延长比赛", artist: "Tank" }, { title: "给我你的爱", artist: "Tank" },
  { title: "我们小时候", artist: "Tank" }, { title: "挺你到底", artist: "Tank" }, { title: "蟑螂小强", artist: "Tank" },
  { title: "如果爱忘了", artist: "戚薇" }, { title: "外滩十八号", artist: "袁成杰/戚薇" }, { title: "为了遇见你", artist: "戚薇" },
  { title: "你是对的人", artist: "戚薇/李承铉" }, { title: "Lucky Lucky", artist: "戚薇/李承铉" }, { title: "仙剑奇侠传", artist: "麦振鸿" },
  { title: "杀破狼", artist: "JS" }, { title: "花与剑", artist: "JS" }, { title: "终于", artist: "JS" },
  { title: "遇见未来", artist: "JS" }, { title: "SAY FOREVER", artist: "JS" }, { title: "苏格拉底的爱", artist: "JS" },
  { title: "也许有一天", artist: "JS" }, { title: "回忆的圣诞节", artist: "JS" }, { title: "我们都寂寞", artist: "JS" },
  { title: "天空的颜色", artist: "JS" }, { title: "我比想象中爱你", artist: "JS" }, { title: "爱情背包客", artist: "JS" },
  { title: "明天", artist: "JS" }, { title: "你是此生最美的风景", artist: "JS" }, { title: "平行线", artist: "JS" },
  { title: "逆风飞行", artist: "JS" }, { title: "飞向札幌的班机", artist: "JS" }, { title: "Harmonia", artist: "JS" },
  { title: "Gorilla", artist: "JS" }, { title: "Sorrento的月光", artist: "JS" }, { title: "A New Break of Dawn", artist: "JS" },
  { title: "Heaven", artist: "JS" }, { title: "Art of Love", artist: "JS" }, { title: "Beautiful World", artist: "JS" },
  { title: "Deep Love", artist: "JS" }, { title: "Earth Song", artist: "JS" }, { title: "Five Days", artist: "JS" },
  { title: "Goodbye", artist: "JS" }, { title: "Happy Birthday", artist: "JS" }, { title: "I Believe", artist: "JS" },
  { title: "Just You and Me", artist: "JS" }, { title: "Keep on Loving You", artist: "JS" }, { title: "Love", artist: "JS" }
];

export const POOL_SHOW = [
  { title: "Manta (Live)", artist: "G.E.M.邓紫棋" }, { title: "Bang Bang (Live)", artist: "G.E.M.邓紫棋/张靓颖" }, { title: "Unstoppable (Live)", artist: "单依纯" },
  { title: "达拉崩吧 (Live)", artist: "周深" }, { title: "齐天 (Live)", artist: "华晨宇" }, { title: "九儿 (Live)", artist: "谭维维" },
  { title: "身骑白马 (Live)", artist: "徐佳莹" }, { title: "永不失联的爱 (Live)", artist: "单依纯" }, { title: "大鱼 (Live)", artist: "周深" },
  { title: "左手指月 (Live)", artist: "萨顶顶" }, { title: "起风了 (Live)", artist: "吴青峰" }, { title: "易燃易爆炸 (Live)", artist: "华晨宇" },
  { title: "默 (Live)", artist: "那英" }, { title: "阿刁 (Live)", artist: "张韶涵" }, { title: "曾经的你 (Live)", artist: "许巍" },
  { title: "平凡之路 (Live)", artist: "朴树" }, { title: "山丘 (Live)", artist: "李宗盛" }, { title: "给自己的歌 (Live)", artist: "李宗盛" },
  { title: "浮夸 (Live)", artist: "陈奕迅" }, { title: "K歌之王 (Live)", artist: "陈奕迅" }, { title: "十年 (Live)", artist: "陈奕迅" },
  { title: "因为爱情 (Live)", artist: "陈奕迅/王菲" }, { title: "笑忘书 (Live)", artist: "王菲" }, { title: "传奇 (Live)", artist: "王菲" },
  { title: "红豆 (Live)", artist: "王菲" }, { title: "人间 (Live)", artist: "王菲" }, { title: "百年孤寂 (Live)", artist: "王菲" },
  { title: "开到荼蘼 (Live)", artist: "王菲" }, { title: "闷 (Live)", artist: "王菲" }, { title: "催眠 (Live)", artist: "王菲" },
  { title: "你快乐所以我快乐 (Live)", artist: "王菲" }, { title: "半途而废 (Live)", artist: "王菲" }, { title: "偿还 (Live)", artist: "王菲" },
  { title: "暧昧 (Live)", artist: "王菲" }, { title: "棋子 (Live)", artist: "王菲" }, { title: "执迷不悔 (Live)", artist: "王菲" },
  { title: "容易受伤的女人 (Live)", artist: "王菲" }, { title: "天空 (Live)", artist: "王菲" }, { title: "我愿意 (Live)", artist: "王菲" },
  { title: "流年 (Live)", artist: "王菲" }, { title: "匆匆那年 (Live)", artist: "王菲" }, { title: "致青春 (Live)", artist: "王菲" },
  { title: "爱与痛的边缘 (Live)", artist: "王菲" }, { title: "梦中人 (Live)", artist: "王菲" }, { title: "暗涌 (Live)", artist: "王菲" },
  { title: "约定 (Live)", artist: "王菲" }, { title: "给自己的情书 (Live)", artist: "王菲" }, { title: "多得他 (Live)", artist: "王菲" },
  { title: "静夜的单簧管 (Live)", artist: "王菲" }, { title: "季候风 (Live)", artist: "王菲" }, { title: "如风 (Live)", artist: "王菲" },
  { title: "冷战 (Live)", artist: "王菲" }, { title: "誓言 (Live)", artist: "王菲" }, { title: "出路 (Live)", artist: "王菲" },
  { title: "讨好自己 (Live)", artist: "王菲" }, { title: "Di-Dar (Live)", artist: "王菲" }, { title: "浮躁 (Live)", artist: "王菲" },
  { title: "堕落 (Live)", artist: "王菲" }, { title: "末日 (Live)", artist: "王菲" }, { title: "怀念 (Live)", artist: "王菲" }
];

export const POOL_OST = [
  { title: "大鱼", artist: "周深" }, { title: "凉凉", artist: "张碧晨/杨宗纬" }, { title: "不染", artist: "毛不易" },
  { title: "时间煮雨", artist: "郁可唯" }, { title: "知否知否", artist: "胡夏/郁可唯" }, { title: "让酒", artist: "摩登兄弟刘宇宁" },
  { title: "三生三世", artist: "张杰" }, { title: "九儿", artist: "韩红" }, { title: "年轮", artist: "张碧晨" },
  { title: "剑心", artist: "张杰" }, { title: "画心", artist: "张靓颖" }, { title: "终于等到你", artist: "张靓颖" },
  { title: "天下无双", artist: "张靓颖" }, { title: "我们说好的", artist: "张靓颖" }, { title: "如果这就是爱情", artist: "张靓颖" },
  { title: "我的梦", artist: "张靓颖" }, { title: "木兰星", artist: "张靓颖" }, { title: "如果爱下去", artist: "张靓颖" },
  { title: "这世界那么多人", artist: "莫文蔚" }, { title: "萱草花", artist: "张小斐" }, { title: "如愿", artist: "王菲" },
  { title: "匆匆那年", artist: "王菲" }, { title: "致青春", artist: "王菲" }, { title: "因为爱情", artist: "王菲/陈奕迅" },
  { title: "在这个世界相遇", artist: "陈奕迅" }, { title: "陪你度过漫长岁月", artist: "陈奕迅" }, { title: "让我留在你身边", artist: "陈奕迅" },
  { title: "我们的明天", artist: "鹿晗" }, { title: "勋章", artist: "鹿晗" }, { title: "心率", artist: "鹿晗" },
  { title: "时间之门", artist: "鹿晗" }, { title: "超级英雄", artist: "鹿晗" }, { title: "诺言", artist: "鹿晗" },
  { title: "致爱", artist: "鹿晗" }, { title: "微白城市", artist: "鹿晗" }, { title: "某时某刻", artist: "鹿晗" },
  { title: "如果", artist: "鹿晗" }, { title: "夜行记", artist: "鹿晗" }, { title: "触发", artist: "鹿晗" },
  { title: "零界点", artist: "鹿晗" }, { title: "冒险时间", artist: "鹿晗" }, { title: "敢", artist: "鹿晗" },
  { title: "体会", artist: "鹿晗" }, { title: "封印", artist: "鹿晗" }, { title: "时差", artist: "鹿晗" },
  { title: "分身", artist: "鹿晗" }, { title: "真我", artist: "鹿晗" }, { title: "原色", artist: "鹿晗" },
  { title: "心率", artist: "鹿晗" }, { title: "剧中人", artist: "鹿晗" }, { title: "怜城辞", artist: "鹿晗" },
  { title: "梦寐之地", artist: "鹿晗" }, { title: "光辉岁月", artist: "Beyond" }, { title: "海阔天空", artist: "Beyond" },
  { title: "真的爱你", artist: "Beyond" }, { title: "喜欢你", artist: "Beyond" }, { title: "大地", artist: "Beyond" },
  { title: "不再犹豫", artist: "Beyond" }, { title: "AMANI", artist: "Beyond" }, { title: "情人", artist: "Beyond" },
  { title: "冷雨夜", artist: "Beyond" }, { title: "再见理想", artist: "Beyond" }, { title: "谁伴我闯荡", artist: "Beyond" },
  { title: "灰色轨迹", artist: "Beyond" }, { title: "岁月无声", artist: "Beyond" }, { title: "长城", artist: "Beyond" },
  { title: "农民", artist: "Beyond" }, { title: "不可一世", artist: "Beyond" }, { title: "无悔这一生", artist: "Beyond" },
  { title: "逝去日子", artist: "Beyond" }, { title: "曾经拥有", artist: "Beyond" }, { title: "未曾后悔", artist: "Beyond" },
  { title: "午夜怨曲", artist: "Beyond" }, { title: "战胜心魔", artist: "Beyond" }, { title: "冲开一切", artist: "Beyond" }
];

export const POOL_WORKOUT = [
  { title: "Summer", artist: "Calvin Harris" }, { title: "Wake Me Up", artist: "Avicii" }, { title: "Titanium", artist: "David Guetta/Sia" },
  { title: "Closer", artist: "The Chainsmokers" }, { title: "Faded", artist: "Alan Walker" }, { title: "Alone", artist: "Marshmello" },
  { title: "Clarity", artist: "Zedd" }, { title: "Animals", artist: "Martin Garrix" }, { title: "The Nights", artist: "Avicii" },
  { title: "Waiting For Love", artist: "Avicii" }, { title: "Levels", artist: "Avicii" }, { title: "Hey Brother", artist: "Avicii" },
  { title: "This Is What You Came For", artist: "Calvin Harris/Rihanna" }, { title: "One Kiss", artist: "Calvin Harris/Dua Lipa" },
  { title: "Blame", artist: "Calvin Harris/John Newman" }, { title: "Outside", artist: "Calvin Harris/Ellie Goulding" },
  { title: "Under Control", artist: "Calvin Harris/Alesso" }, { title: "I Need Your Love", artist: "Calvin Harris/Ellie Goulding" },
  { title: "Sweet Nothing", artist: "Calvin Harris/Florence Welch" }, { title: "Feel So Close", artist: "Calvin Harris" },
  { title: "Bounce", artist: "Calvin Harris" }, { title: "How Deep Is Your Love", artist: "Calvin Harris" }, { title: "My Way", artist: "Calvin Harris" },
  { title: "Slide", artist: "Calvin Harris" }, { title: "Heatstroke", artist: "Calvin Harris" }, { title: "Rollin", artist: "Calvin Harris" },
  { title: "Feels", artist: "Calvin Harris" }, { title: "Faking It", artist: "Calvin Harris" }, { title: "Hard to Love", artist: "Calvin Harris" },
  { title: "Skrt On Me", artist: "Calvin Harris" }, { title: "Holiday", artist: "Calvin Harris" }, { title: "Cash Out", artist: "Calvin Harris" },
  { title: "Pray to God", artist: "Calvin Harris" }, { title: "Open Wide", artist: "Calvin Harris" }, { title: "Together", artist: "Calvin Harris" },
  { title: "Burnin", artist: "Calvin Harris" }, { title: "Dollar Signs", artist: "Calvin Harris" }, { title: "Slow Acid", artist: "Calvin Harris" },
  { title: "Faith", artist: "Calvin Harris" }, { title: "Thinking About You", artist: "Calvin Harris" }, { title: "Drinking from the Bottle", artist: "Calvin Harris" },
  { title: "Iron", artist: "Calvin Harris" }, { title: "School", artist: "Calvin Harris" }, { title: "Here 2 China", artist: "Calvin Harris" },
  { title: "Let's Go", artist: "Calvin Harris" }, { title: "Awooga", artist: "Calvin Harris" }, { title: "We'll Be Coming Back", artist: "Calvin Harris" },
  { title: "Mansion", artist: "Calvin Harris" }, { title: "Ready for the Weekend", artist: "Calvin Harris" }, { title: "Flashback", artist: "Calvin Harris" },
  { title: "The Rain", artist: "Calvin Harris" }, { title: "Limit to Your Love", artist: "Calvin Harris" }, { title: "Blue", artist: "Calvin Harris" },
  { title: "Stars Come Out", artist: "Calvin Harris" }, { title: "You Used to Hold Me", artist: "Calvin Harris" }, { title: "Worst Day", artist: "Calvin Harris" },
  { title: "50 Ways to Say Goodbye", artist: "Train" }, { title: "Drive By", artist: "Train" }, { title: "Hey, Soul Sister", artist: "Train" },
  { title: "Marry Me", artist: "Train" }, { title: "Drops of Jupiter", artist: "Train" }, { title: "Calling All Angels", artist: "Train" }
];

export const POOL_VITALITY_GIRLS = [
  { title: "日不落(电影 《记忆的裂痕》 插曲)", artist: "蔡依林" },
  { title: "恶作剧", artist: "林依晨" },
  { title: "彩虹的微笑", artist: "王心凌" },
  { title: "爱丫爱丫 (电视剧 《爱情是从告白开始的》 插曲)", artist: "BY2" },
  { title: "胆小鬼", artist: "梁咏琪" },
  { title: "现在不跳舞要干嘛", artist: "徐佳莹" },
  { title: "爱情三十六计", artist: "蔡依林" },
  { title: "爱你", artist: "王心凌" },
  { title: "我的未来式(电视剧 《爱情公寓》 片头曲)", artist: "郭采洁" },
  { title: "说爱你(电影 《我要飞上天》 主题曲)", artist: "蔡依林" },
  { title: "管他什么音乐", artist: "范晓萱&100%乐团" },
  { title: "庆祝", artist: "杨丞琳" },
  { title: "超级喜欢", artist: "卓文萱" },
  { title: "淋雨一直走", artist: "张韶涵" },
  { title: "第一天", artist: "孙燕姿" },
  { title: "Honey", artist: "王心凌" },
  { title: "圈住你 (完整版)", artist: "一口甜" },
  { title: "最初的梦想", artist: "范玮琪" },
  { title: "红色高跟鞋 (电影 《爱呼2：爱情左右》 主题曲)", artist: "蔡健雅" },
  { title: "世界上的另一个我", artist: "阿肆 / 郭采洁" },
  { title: "我爱他 (电视剧 《下一站，幸福》 主题曲)", artist: "丁当" },
  { title: "一个像夏天一个像秋天", artist: "庄心妍" },
  { title: "New Boy", artist: "房东的猫" }
];
