export const SHOW_SONG_LIST = [
  { title: "爱就一个字 (live)", artist: "张信哲 / 庾澄庆 / 苏有朋 / A-Lin / 黄绮珊" },
  { title: "天后 (live | 典藏)", artist: "李佳薇" },
  { title: "爱错 (live)", artist: "A-Lin / 王赫野" },
  { title: "成全(蒙面唱将猜猜猜)", artist: "林宥嘉" },
  { title: "永不失联的爱 (2020中国好声音第3期)", artist: "单依纯" },
  { title: "陌生人(蒙面唱将)", artist: "苏运莹 / 冯提莫 / 吴青峰" },
  { title: "泪桥 (Live)", artist: "张震岳 / Ghost (王琳凯)" },
  { title: "达尔文(Live)", artist: "丁当" },
  { title: "囍帖街(Live)", artist: "陈奕迅" },
  { title: "一个人想着一个人 (Live)", artist: "Ghost (王琳凯) / 武艺" },
  { title: "岁月神偷(蒙面唱将猜猜猜)", artist: "李慧珍 / 陈楚生" },
  { title: "独家记忆 (Live)", artist: "郁可唯" },
  { title: "梦一场 (live | 典藏)", artist: "单依纯" },
  { title: "孤单Tequila (live | 典藏)", artist: "A-Lin" },
  { title: "故乡的云 (live)", artist: "那英 / 孙楠 / 庾澄庆 / 苏有朋 / A-Lin / 黄绮珊" },
  { title: "她说 (Live)", artist: "杨丞琳 / 周深" },
  { title: "伤痕 (live | 典藏)", artist: "A-Lin / 彭佳慧" },
  { title: "静止 (蒙面唱将猜猜猜)", artist: "大张伟 / 杨乃文" },
  { title: "匿名的好友 (live)", artist: "李佳薇 / 徐子未" },
  { title: "晴 (live)", artist: "汪苏泷" },
  { title: "一点 (Live)", artist: "姚晓棠 / 黄子弘凡" },
  { title: "一直很安静 (live)", artist: "颜人中" },
  { title: "活该(Live)", artist: "陈楚生 / 王栎鑫 / 陆虎 / 张远 / 苏醒 / 王铮亮" },
  { title: "爱如潮水(蒙面唱将猜猜猜)", artist: "GAI周延" },
  { title: "若月亮没来 (Live)", artist: "王宇宙Leto / 武艺 / 朱星杰" },
  { title: "行走的鱼 (live | 典藏)", artist: "陈楚生" },
  { title: "不值得 (Live)", artist: "单依纯" },
  { title: "唯一(蒙面唱将)", artist: "李玖哲 / 萧敬腾" },
  { title: "屋顶 (live)", artist: "Eric周兴哲 / 姚晓棠" },
  { title: "忘不了 (蒙面唱将猜猜猜)", artist: "大张伟 / 王太利" },
  { title: "原来你也在这里(蒙面唱将猜猜猜)", artist: "苏慧伦" },
  { title: "分开旅行 (live)", artist: "黄龄 / 王赫野" },
  { title: "流沙 (live)", artist: "Eric周兴哲 / 欧阳靖" },
  { title: "不如回家喝自来水 (live)", artist: "胡夏 / Feezy / TOP登陆少年-张泽禹 / TOP登陆少年-左航" },
  { title: "给电影人的情书 (2020中国好声音第12期)", artist: "单依纯" },
  { title: "左转灯 (1000 Times +1) (live)", artist: "汪苏泷 / Eric周兴哲" },
  { title: "推开世界的门 (Live)", artist: "张震岳 / 黄子弘凡" },
  { title: "慢慢喜欢你(Live at EasON AIR)", artist: "陈奕迅" },
  { title: "世界末日(Live版)", artist: "周杰伦" },
  { title: "这世界那么多人 (Live)", artist: "张碧晨 / 王赫野" },
  { title: "追光者(蒙面唱将猜猜猜)", artist: "汪苏泷" },
  { title: "忽然之间(蒙面唱将)", artist: "毛不易 / 陈粒" },
  { title: "倾城 (live | 典藏)", artist: "卫兰" },
  { title: "此生不换 (live)", artist: "黄霄云" },
  { title: "数到十 (live)", artist: "苏有朋 / 林宥嘉" },
  { title: "月光爱人 (live)", artist: "A-Lin" },
  { title: "离开我的依赖 (live)", artist: "王赫野 / 黄霄云" },
  { title: "为你写诗(Live)", artist: "汪苏泷" },
  { title: "决爱 (live | 典藏)", artist: "李佳薇" },
  { title: "只要有你 (live)", artist: "那英 / 孙楠" },
  { title: "瓦解(Live)", artist: "周杰伦" },
  { title: "兜圈 (live)", artist: "林宥嘉" },
  { title: "言不由衷(蒙面唱将)", artist: "毛不易" },
  { title: "如果的事 (Live)", artist: "张碧晨 / 陈卓璇" },
  { title: "落叶归根 (live | 典藏)", artist: "单依纯 / 王力宏" },
  { title: "气球 (live)", artist: "庾澄庆 / 黄龄" },
  { title: "全世界下雨(Live)", artist: "周深" }
];
