export const WORKOUT_SONG_LIST = [
  { title: "爱无赦", artist: "蔡依林" },
  { title: "不如跳舞", artist: "陈慧琳" },
  { title: "Ape Shall Never Kill Ape", artist: "欧阳靖" },
  { title: "潇洒小姐", artist: "萧亚轩" },
  { title: "大艺术家", artist: "蔡依林" },
  { title: "向前冲", artist: "徐怀钰" },
  { title: "本草纲目", artist: "周杰伦" },
  { title: "绝对无敌(电视剧《篮球火》主题曲)", artist: "倪子冈" },
  { title: "算你狠", artist: "陈小春" },
  { title: "Flow", artist: "方大同 / 王力宏" },
  { title: "与狼共舞", artist: "许慧欣" },
  { title: "看我72变(游戏《神之领域首部曲恶魔岛》主题曲)", artist: "蔡依林" },
  { title: "Ring Ring Ring", artist: "S.H.E" },
  { title: "我的答铃 Dance Remix", artist: "美美jocie" },
  { title: "王妃", artist: "萧敬腾" },
  { title: "玩爱之徒(I Know You Remix)", artist: "蔡依林" },
  { title: "我就是我", artist: "萧亚轩" },
  { title: "大丈夫", artist: "蔡依林" },
  { title: "噢买尬", artist: "五月天" },
  { title: "唇唇欲动", artist: "蔡依林" },
  { title: "我的麦克风", artist: "潘玮柏" },
  { title: "OAOA (现在就是永远)(纪录片《五月天追梦3DNA》主题曲)", artist: "五月天" },
  { title: "孤单芭蕾", artist: "许慧欣" },
  { title: "特务J", artist: "蔡依林" },
  { title: "闪闪惹人爱", artist: "萧亚轩" },
  { title: "青春斗(电视剧《海派甜心》插曲)", artist: "杨丞琳" },
  { title: "Hk Superstar (电影《速度与激情6》插曲)", artist: "欧阳靖 / 吴彦祖" },
  { title: "Mr.Q", artist: "蔡依林" },
  { title: "Lay Your Love", artist: "许慧欣" },
  { title: "OH LA LA LA", artist: "蔡依林" },
  { title: "Prove It", artist: "蔡依林" },
  { title: "蛇舞", artist: "周杰伦 / 梁心颐" },
  { title: "浪漫来袭", artist: "萧亚轩" },
  { title: "护花使者(电影《西虹市首富》插曲)", artist: "李克勤" },
  { title: "野蛮游戏", artist: "蔡依林" },
  { title: "结果咧", artist: "大嘴巴" },
  { title: "忍者", artist: "周杰伦" },
  { title: "Tell Me", artist: "潘玮柏 / 徐洁儿" },
  { title: "撑腰", artist: "罗志祥" },
  { title: "有几坏", artist: "钟欣潼 / 陈奂仁 / 陈冠希" },
  { title: "追杀邱比特", artist: "蔡依林" },
  { title: "独立宣言", artist: "许慧欣" },
  { title: "龙拳", artist: "周杰伦" },
  { title: "爱疯头 (电视剧《海派甜心》片头曲)", artist: "罗志祥" },
  { title: "自由", artist: "张震岳" },
  { title: "爱的主打歌", artist: "萧亚轩" },
  { title: "任意门", artist: "杨丞琳" },
  { title: "我的果汁分你一半", artist: "花儿乐队" },
  { title: "不怕 不怕 (电影《下一站再爱你》主题曲)", artist: "美美jocie" },
  { title: "Pleasure", artist: "蔡依林" },
  { title: "爱情三十六计", artist: "蔡依林" },
  { title: "睁一只眼闭一只眼", artist: "蔡依林" },
  { title: "跨时代", artist: "周杰伦" },
  { title: "DIY", artist: "蔡依林" },
  { title: "壁虎漫步", artist: "潘玮柏" },
  { title: "SEVEN", artist: "蔡依林" },
  { title: "火", artist: "张惠妹" },
  { title: "日不落(电影《记忆的裂痕》插曲)", artist: "蔡依林" },
  { title: "花蝴蝶", artist: "蔡依林" },
  { title: "我要飞", artist: "F.I.R.飞儿乐团" },
  { title: "胡撸胡撸瓢儿Remix", artist: "大张伟" },
  { title: "我喜欢", artist: "梁静茹" },
  { title: "铿锵玫瑰", artist: "林忆莲" },
  { title: "萤火(电视剧《我们的少年时代》插曲)", artist: "TFBOYS" },
  { title: "等一个他", artist: "G.E.M.邓紫棋" },
  { title: "盲点", artist: "周笔畅" },
  { title: "就这样吗 (电视剧《不惑之旅》主题曲)", artist: "周笔畅" },
  { title: "如果当时", artist: "许嵩" },
  { title: "盛夏光年(电影《盛夏光年》主题曲)", artist: "五月天 阿信" },
  { title: "有形的翅膀", artist: "张韶涵" },
  { title: "追光者(蒙面唱将猜猜猜)", artist: "汪苏泷" },
  { title: "骄傲", artist: "王源" },
  { title: "逐空·高考战歌(上岸版)", artist: "叶斯淳 / 菜籽油Clazy" },
  { title: "我是如此相信", artist: "周杰伦" },
  { title: "最重要的小事", artist: "五月天" },
  { title: "简单爱", artist: "周杰伦" },
  { title: "与我无关", artist: "陈势安" },
  { title: "一路向北 (电影《头文字D》插曲)", artist: "周杰伦" },
  { title: "勋章 (电影《我是证人》主题曲)", artist: "鹿晗" },
  { title: "花海", artist: "周杰伦" }
];
